version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: bus_tracking_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bus_tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: bus_tracking_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/bus_tracking
    depends_on:
      - postgres

volumes:
  postgres_data:
